channels:
- conda-forge
dependencies:
- jupyterlab=0.35
- jupyter_dash
- geopandas 
- python=3.7
- pip:
  - dash==0.35.1
  - dash-html-components==0.13.4
  - dash-core-components==0.42.1
  - dash-table==3.1.11
